<?php

namespace App\Services;

class InvestmentCatalog
{
    public static function all(): array
    {
        return [
            [
                'id' => 'nvidia',
                'asset_name' => 'Nvidia',
                'symbol' => 'NVDA',
                'asset_type' => 'stocks',
                'quantity' => 14,
                'buy_price' => 24500,
                'current_price' => 31200,
                'roi' => 27.35,
                'risk_level' => 'medium',
                'sector' => 'AI Semiconductors',
                'growth' => 5.8,
                'description' => 'AI infrastructure leader with strong earnings momentum and a dominant GPU ecosystem.',
                'market_cap' => '₹286.9T',
                'volatility' => 'High',
                'last_updated' => now()->subMinutes(12)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'tesla',
                'asset_name' => 'Tesla',
                'symbol' => 'TSLA',
                'asset_type' => 'stocks',
                'quantity' => 10,
                'buy_price' => 17200,
                'current_price' => 20150,
                'roi' => 17.15,
                'risk_level' => 'medium',
                'sector' => 'EV & Mobility',
                'growth' => 4.9,
                'description' => 'High-beta EV manufacturer with strong momentum and a fast-moving product roadmap.',
                'market_cap' => '₹184.2T',
                'volatility' => 'High',
                'last_updated' => now()->subMinutes(8)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'apple',
                'asset_name' => 'Apple',
                'symbol' => 'AAPL',
                'asset_type' => 'stocks',
                'quantity' => 18,
                'buy_price' => 15100,
                'current_price' => 18400,
                'roi' => 21.85,
                'risk_level' => 'medium',
                'sector' => 'Technology',
                'growth' => 2.4,
                'description' => 'Blue-chip consumer technology stock with premium hardware and services economics.',
                'market_cap' => '₹317.4T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(16)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'sbi',
                'asset_name' => 'SBI',
                'symbol' => 'SBIN',
                'asset_type' => 'stocks',
                'quantity' => 55,
                'buy_price' => 710,
                'current_price' => 872,
                'roi' => 22.82,
                'risk_level' => 'medium',
                'sector' => 'Banking',
                'growth' => 2.7,
                'description' => 'Public-sector bank with improving credit quality and operating leverage.',
                'market_cap' => '₹7.8T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(10)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'solana',
                'asset_name' => 'Solana',
                'symbol' => 'SOL',
                'asset_type' => 'crypto',
                'quantity' => 75,
                'buy_price' => 11500,
                'current_price' => 13547,
                'roi' => 17.80,
                'risk_level' => 'high',
                'sector' => 'Blockchain Infrastructure',
                'growth' => 5.4,
                'description' => 'Fast blockchain network with growing developer activity and ecosystem breadth.',
                'market_cap' => '₹18.6T',
                'volatility' => 'Very High',
                'last_updated' => now()->subMinutes(6)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'bitcoin',
                'asset_name' => 'Bitcoin',
                'symbol' => 'BTC',
                'asset_type' => 'crypto',
                'quantity' => 0.18,
                'buy_price' => 4200000,
                'current_price' => 4919444,
                'roi' => 16.89,
                'risk_level' => 'high',
                'sector' => 'Digital Assets',
                'growth' => 4.2,
                'description' => 'Largest digital asset with strong institutional adoption and high volatility.',
                'market_cap' => '₹96.2T',
                'volatility' => 'Very High',
                'last_updated' => now()->subMinutes(3)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'ethereum',
                'asset_name' => 'Ethereum',
                'symbol' => 'ETH',
                'asset_type' => 'crypto',
                'quantity' => 2.5,
                'buy_price' => 210000,
                'current_price' => 239700,
                'roi' => 14.14,
                'risk_level' => 'high',
                'sector' => 'Smart Contracts',
                'growth' => 3.6,
                'description' => 'Smart contract network powering DeFi, NFTs, and on-chain applications.',
                'market_cap' => '₹44.8T',
                'volatility' => 'High',
                'last_updated' => now()->subMinutes(14)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'gold-etf',
                'asset_name' => 'Gold ETF',
                'symbol' => 'GOLD',
                'asset_type' => 'etf',
                'quantity' => 45,
                'buy_price' => 5850,
                'current_price' => 6463,
                'roi' => 10.48,
                'risk_level' => 'low',
                'sector' => 'Commodities',
                'growth' => 1.8,
                'description' => 'Inflation hedge and low-correlation defensive allocation.',
                'market_cap' => '₹3.8T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(20)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'silver-etf',
                'asset_name' => 'Silver ETF',
                'symbol' => 'SILVER',
                'asset_type' => 'etf',
                'quantity' => 110,
                'buy_price' => 68,
                'current_price' => 74.82,
                'roi' => 10.03,
                'risk_level' => 'low',
                'sector' => 'Commodities',
                'growth' => 1.4,
                'description' => 'Precious metal exposure for diversification and inflation protection.',
                'market_cap' => '₹1.2T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(22)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'reliance',
                'asset_name' => 'Reliance',
                'symbol' => 'RELIANCE',
                'asset_type' => 'stocks',
                'quantity' => 22,
                'buy_price' => 2860,
                'current_price' => 3190,
                'roi' => 11.54,
                'risk_level' => 'medium',
                'sector' => 'Conglomerate',
                'growth' => 1.6,
                'description' => 'Diversified blue-chip with energy, telecom, retail, and digital exposure.',
                'market_cap' => '₹21.7T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(31)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'tcs',
                'asset_name' => 'TCS',
                'symbol' => 'TCS',
                'asset_type' => 'stocks',
                'quantity' => 16,
                'buy_price' => 3550,
                'current_price' => 4208,
                'roi' => 18.55,
                'risk_level' => 'low',
                'sector' => 'IT Services',
                'growth' => 1.9,
                'description' => 'Large-cap IT services leader with stable margins and enterprise relationships.',
                'market_cap' => '₹14.9T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(34)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'hdfc-bank',
                'asset_name' => 'HDFC Bank',
                'symbol' => 'HDFCBANK',
                'asset_type' => 'stocks',
                'quantity' => 30,
                'buy_price' => 1480,
                'current_price' => 1697,
                'roi' => 14.66,
                'risk_level' => 'low',
                'sector' => 'Banking',
                'growth' => 1.5,
                'description' => 'Private-sector banking heavyweight with broad retail franchise and solid credit quality.',
                'market_cap' => '₹11.4T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(35)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'mutual-fund',
                'asset_name' => 'Nifty 50 Mutual Fund',
                'symbol' => 'NIFTY50MF',
                'asset_type' => 'mutual_funds',
                'quantity' => 240,
                'buy_price' => 118.5,
                'current_price' => 132.92,
                'roi' => 12.17,
                'risk_level' => 'low',
                'sector' => 'Diversified Equity',
                'growth' => 1.2,
                'description' => 'Broad-market mutual fund for disciplined long-term wealth creation and diversification.',
                'market_cap' => '₹1.1T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(38)->toISOString(),
                'status' => 'held',
                'watchlisted' => true,
            ],
            [
                'id' => 'microsoft',
                'asset_name' => 'Microsoft',
                'symbol' => 'MSFT',
                'asset_type' => 'stocks',
                'quantity' => 12,
                'buy_price' => 30800,
                'current_price' => 35958,
                'roi' => 16.74,
                'risk_level' => 'medium',
                'sector' => 'Cloud & AI',
                'growth' => 2.7,
                'description' => 'Enterprise software and cloud franchise with stable cash flows.',
                'market_cap' => '₹289.7T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(11)->toISOString(),
                'status' => 'held',
                'watchlisted' => false,
            ],
            [
                'id' => 'google',
                'asset_name' => 'Google',
                'symbol' => 'GOOGL',
                'asset_type' => 'stocks',
                'quantity' => 9,
                'buy_price' => 24200,
                'current_price' => 28011,
                'roi' => 15.75,
                'risk_level' => 'medium',
                'sector' => 'Internet Platforms',
                'growth' => 2.4,
                'description' => 'Search and advertising giant with growing cloud and AI monetization upside.',
                'market_cap' => '₹245.4T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(15)->toISOString(),
                'status' => 'watchlist',
                'watchlisted' => true,
            ],
            [
                'id' => 'adani-ports',
                'asset_name' => 'Adani Ports',
                'symbol' => 'ADANIPORTS',
                'asset_type' => 'stocks',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 1452,
                'roi' => 0,
                'risk_level' => 'medium',
                'sector' => 'Logistics',
                'growth' => 2.1,
                'description' => 'Infrastructure and logistics platform with long-term trade volume potential.',
                'market_cap' => '₹3.1T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(40)->toISOString(),
                'status' => 'available',
                'watchlisted' => false,
            ],
            [
                'id' => 'infosys',
                'asset_name' => 'Infosys',
                'symbol' => 'INFY',
                'asset_type' => 'stocks',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 1680,
                'roi' => 0,
                'risk_level' => 'low',
                'sector' => 'IT Services',
                'growth' => 1.7,
                'description' => 'Large-cap IT services stock with steady deal wins and margin discipline.',
                'market_cap' => '₹6.9T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(41)->toISOString(),
                'status' => 'available',
                'watchlisted' => false,
            ],
            [
                'id' => 'jio-finance',
                'asset_name' => 'Jio Financial',
                'symbol' => 'JIOFIN',
                'asset_type' => 'stocks',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 312,
                'roi' => 0,
                'risk_level' => 'medium',
                'sector' => 'Financial Services',
                'growth' => 3.0,
                'description' => 'New-age financial services platform with broad ecosystem leverage.',
                'market_cap' => '₹1.9T',
                'volatility' => 'High',
                'last_updated' => now()->subMinutes(43)->toISOString(),
                'status' => 'available',
                'watchlisted' => false,
            ],
            [
                'id' => 'nifty-etf',
                'asset_name' => 'Nifty 50 ETF',
                'symbol' => 'NIFTYETF',
                'asset_type' => 'etf',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 241,
                'roi' => 0,
                'risk_level' => 'low',
                'sector' => 'Broad Market',
                'growth' => 1.1,
                'description' => 'Low-cost index ETF for long-term diversified exposure to large-cap India.',
                'market_cap' => '₹0.9T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(45)->toISOString(),
                'status' => 'available',
                'watchlisted' => true,
            ],
            [
                'id' => 'bond-fund',
                'asset_name' => 'Corporate Bond Fund',
                'symbol' => 'CORPBOND',
                'asset_type' => 'mutual_funds',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 104.35,
                'roi' => 0,
                'risk_level' => 'low',
                'sector' => 'Fixed Income',
                'growth' => 0.8,
                'description' => 'Income-oriented fixed-income fund for stability and lower drawdowns.',
                'market_cap' => '₹0.4T',
                'volatility' => 'Low',
                'last_updated' => now()->subMinutes(47)->toISOString(),
                'status' => 'available',
                'watchlisted' => false,
            ],
            [
                'id' => 'uranium-etf',
                'asset_name' => 'Uranium ETF',
                'symbol' => 'URANIUM',
                'asset_type' => 'commodities',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 119.8,
                'roi' => 0,
                'risk_level' => 'high',
                'sector' => 'Commodities',
                'growth' => 6.4,
                'description' => 'Speculative commodity theme with high beta and strong momentum.',
                'market_cap' => '₹0.2T',
                'volatility' => 'Very High',
                'last_updated' => now()->subMinutes(50)->toISOString(),
                'status' => 'available',
                'watchlisted' => false,
            ],
            [
                'id' => 'reit-fund',
                'asset_name' => 'REIT Fund',
                'symbol' => 'REITX',
                'asset_type' => 'mutual_funds',
                'quantity' => 0,
                'buy_price' => 0,
                'current_price' => 92.4,
                'roi' => 0,
                'risk_level' => 'medium',
                'sector' => 'Real Estate',
                'growth' => 1.3,
                'description' => 'Income-generating real estate exposure with diversified commercial holdings.',
                'market_cap' => '₹0.7T',
                'volatility' => 'Medium',
                'last_updated' => now()->subMinutes(52)->toISOString(),
                'status' => 'available',
                'watchlisted' => false,
            ],
        ];
    }
}
